// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/providers/transaction_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:expense_tracker/models/category.dart' as _i6;
import 'package:expense_tracker/models/transaction.dart' as _i7;
import 'package:expense_tracker/models/user.dart' as _i5;
import 'package:expense_tracker/services/database_helper.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> setDatabaseForTest(_i2.Database? db) => (super.noSuchMethod(
        Invocation.method(
          #setDatabaseForTest,
          [db],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> registerUser(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>?> authenticateUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<_i5.User?> getUserById(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);

  @override
  _i4.Future<int> updateUserProfile(
    int? userId,
    String? name,
    String? avatarUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            userId,
            name,
            avatarUrl,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> changePassword(
    int? userId,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            userId,
            newPassword,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i6.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Category>>.value(<_i6.Category>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i4.Future<List<_i6.Category>>);

  @override
  _i4.Future<List<_i6.Category>> getCategoriesByType(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesByType,
          [type],
        ),
        returnValue: _i4.Future<List<_i6.Category>>.value(<_i6.Category>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i4.Future<List<_i6.Category>>);

  @override
  _i4.Future<_i6.Category?> getCategoryById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i4.Future<_i6.Category?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.Category?>.value(),
      ) as _i4.Future<_i6.Category?>);

  @override
  _i4.Future<int> insertTransaction(_i7.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTransaction,
          [transaction],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i7.Transaction>> getTransactions(
    int? userId, {
    String? type,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [userId],
          {
            #type: type,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<List<_i7.Transaction>>.value(<_i7.Transaction>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.Transaction>>.value(<_i7.Transaction>[]),
      ) as _i4.Future<List<_i7.Transaction>>);

  @override
  _i4.Future<_i7.Transaction?> getTransactionById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionById,
          [id],
        ),
        returnValue: _i4.Future<_i7.Transaction?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.Transaction?>.value(),
      ) as _i4.Future<_i7.Transaction?>);

  @override
  _i4.Future<int> updateTransaction(_i7.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [transaction],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteTransaction(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [id],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<double> getTotalIncome(
    int? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalIncome,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<double> getTotalExpense(
    int? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalExpense,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<double> getBalance(
    int? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<double>.value(0.0),
        returnValueForMissingStub: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<Map<String, double>> getCategoryStats(
    int? userId,
    String? type,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryStats,
          [
            userId,
            type,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<Map<String, double>>.value(<String, double>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i4.Future<Map<String, double>>);
}
