analyzer:
  errors:
    # Giảm cảnh báo cho deprecated methods
    deprecated_member_use: warning
    
    # Bỏ qua lỗi unused imports trong development
    unused_import: warning
    
    # Bỏ qua lỗi avoid_print trong development
    avoid_print: ignore
    
    # Giảm cảnh báo về async gaps
    use_build_context_synchronously: warning
    
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - 'build/**'
    - '.dart_tool/**'

linter:
  rules:
    # Bật các rule cơ bản
    - always_declare_return_types
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_this
    - unrelated_type_equality_checks
    - valid_regexps
    
    # Tắt các rule gây nhiều warning
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - sort_child_properties_last
    - unnecessary_to_list_in_spreads
    - no_leading_underscores_for_local_identifiers