// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:expense_tracker/models/category.dart' as _i2;
import 'package:expense_tracker/models/transaction.dart' as _i5;
import 'package:expense_tracker/providers/auth_provider.dart' as _i9;
import 'package:expense_tracker/providers/theme_provider.dart' as _i10;
import 'package:expense_tracker/providers/transaction_provider.dart' as _i4;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategory_0 extends _i1.SmartFake implements _i2.Category {
  _FakeCategory_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_1 extends _i1.SmartFake implements _i3.ThemeData {
  _FakeThemeData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [TransactionProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionProvider extends _i1.Mock
    implements _i4.TransactionProvider {
  MockTransactionProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Transaction> get transactions => (super.noSuchMethod(
        Invocation.getter(#transactions),
        returnValue: <_i5.Transaction>[],
      ) as List<_i5.Transaction>);

  @override
  List<_i5.Transaction> get allTransactions => (super.noSuchMethod(
        Invocation.getter(#allTransactions),
        returnValue: <_i5.Transaction>[],
      ) as List<_i5.Transaction>);

  @override
  double get totalIncome => (super.noSuchMethod(
        Invocation.getter(#totalIncome),
        returnValue: 0.0,
      ) as double);

  @override
  double get totalExpense => (super.noSuchMethod(
        Invocation.getter(#totalExpense),
        returnValue: 0.0,
      ) as double);

  @override
  double get balance => (super.noSuchMethod(
        Invocation.getter(#balance),
        returnValue: 0.0,
      ) as double);

  @override
  List<_i2.Category> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i2.Category>[],
      ) as List<_i2.Category>);

  @override
  List<_i2.Category> get expenseCategories => (super.noSuchMethod(
        Invocation.getter(#expenseCategories),
        returnValue: <_i2.Category>[],
      ) as List<_i2.Category>);

  @override
  List<_i2.Category> get incomeCategories => (super.noSuchMethod(
        Invocation.getter(#incomeCategories),
        returnValue: <_i2.Category>[],
      ) as List<_i2.Category>);

  @override
  String get searchKeyword => (super.noSuchMethod(
        Invocation.getter(#searchKeyword),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#searchKeyword),
        ),
      ) as String);

  @override
  String get timeFilter => (super.noSuchMethod(
        Invocation.getter(#timeFilter),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#timeFilter),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> loadInitialData() => (super.noSuchMethod(
        Invocation.method(
          #loadInitialData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadTransactions(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #loadTransactions,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void setTransactionsForTest(List<_i5.Transaction>? transactions) =>
      super.noSuchMethod(
        Invocation.method(
          #setTransactionsForTest,
          [transactions],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> addTransaction(_i5.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTransaction,
          [transaction],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateTransaction(_i5.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [transaction],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteTransaction(
    int? id,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [
            id,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void setSearchKeyword(String? keyword) => super.noSuchMethod(
        Invocation.method(
          #setSearchKeyword,
          [keyword],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedCategory(String? category) => super.noSuchMethod(
        Invocation.method(
          #setSelectedCategory,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTimeFilter(String? filter) => super.noSuchMethod(
        Invocation.method(
          #setTimeFilter,
          [filter],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedType(String? type) => super.noSuchMethod(
        Invocation.method(
          #setSelectedType,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilters() => super.noSuchMethod(
        Invocation.method(
          #clearFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Category getCategoryById(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [categoryId],
        ),
        returnValue: _FakeCategory_0(
          this,
          Invocation.method(
            #getCategoryById,
            [categoryId],
          ),
        ),
      ) as _i2.Category);

  @override
  Map<String, double> getCategoryAnalysis(String? type) => (super.noSuchMethod(
        Invocation.method(
          #getCategoryAnalysis,
          [type],
        ),
        returnValue: <String, double>{},
      ) as Map<String, double>);

  @override
  List<double> getMonthlyData(
    int? year,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyData,
          [
            year,
            type,
          ],
        ),
        returnValue: <double>[],
      ) as List<double>);

  @override
  Map<String, double> getWeeklyData(
    DateTime? startDate,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyData,
          [
            startDate,
            type,
          ],
        ),
        returnValue: <String, double>{},
      ) as Map<String, double>);

  @override
  List<_i5.Transaction> getRecentTransactions(int? limit) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentTransactions,
          [limit],
        ),
        returnValue: <_i5.Transaction>[],
      ) as List<_i5.Transaction>);

  @override
  List<_i5.Transaction> getTransactionsByCategory(int? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsByCategory,
          [categoryId],
        ),
        returnValue: <_i5.Transaction>[],
      ) as List<_i5.Transaction>);

  @override
  _i5.Transaction? getTransactionById(int? id) =>
      (super.noSuchMethod(Invocation.method(
        #getTransactionById,
        [id],
      )) as _i5.Transaction?);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i9.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<Map<String, dynamic>> register({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> updateProfile({
    required String? name,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #name: name,
            #avatarUrl: avatarUrl,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #currentPassword: currentPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  void setUserDataForTest({
    required int? userId,
    required String? name,
    required String? email,
    String? avatar,
    DateTime? createdAt,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setUserDataForTest,
          [],
          {
            #userId: userId,
            #name: name,
            #email: email,
            #avatar: avatar,
            #createdAt: createdAt,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i10.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i3.ThemeMode.system,
      ) as _i3.ThemeMode);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> setThemeMode(_i3.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void toggleTheme() => super.noSuchMethod(
        Invocation.method(
          #toggleTheme,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ThemeData getTheme(_i3.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #getTheme,
          [context],
        ),
        returnValue: _FakeThemeData_1(
          this,
          Invocation.method(
            #getTheme,
            [context],
          ),
        ),
      ) as _i3.ThemeData);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
